// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#include "Robot.h"

#include "TeleopDrive.h"


TeleopDrive::TeleopDrive(): Command() {
       Requires(Robot::driveTrain.get());
}

void TeleopDrive::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void TeleopDrive::Execute() {
Robot::driveTrain->TDrive(Robot::oi->getJoystick1());
}

// Make this return true when this Command no longer needs to run execute()
bool TeleopDrive::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void TeleopDrive::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TeleopDrive::Interrupted() {

}
