// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveTrainSpeedController1;
std::shared_ptr<SpeedController> RobotMap::driveTrainSpeedController2;
std::shared_ptr<SpeedController> RobotMap::driveTrainSpeedController3;
std::shared_ptr<SpeedController> RobotMap::driveTrainSpeedController4;
std::shared_ptr<RobotDrive> RobotMap::driveTrainRobotDrive41;
std::shared_ptr<AnalogGyro> RobotMap::gyro;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    gyro.reset(new AnalogGyro(0));
    lw->AddActuator("DriveTrain", "Gyro", std::static_pointer_cast<AnalogGyro>(gyro));

    driveTrainSpeedController1.reset(new Talon(0));
    lw->AddActuator("DriveTrain", "Speed Controller 1", std::static_pointer_cast<Talon>(driveTrainSpeedController1));
    
    driveTrainSpeedController2.reset(new Talon(1));
    lw->AddActuator("DriveTrain", "Speed Controller 2", std::static_pointer_cast<Talon>(driveTrainSpeedController2));
    
    driveTrainSpeedController3.reset(new Talon(2));
    lw->AddActuator("DriveTrain", "Speed Controller 3", std::static_pointer_cast<Talon>(driveTrainSpeedController3));
    
    driveTrainSpeedController4.reset(new Talon(3));
    lw->AddActuator("DriveTrain", "Speed Controller 4", std::static_pointer_cast<Talon>(driveTrainSpeedController4));
    
    driveTrainRobotDrive41.reset(new RobotDrive(driveTrainSpeedController1, driveTrainSpeedController2,
              driveTrainSpeedController3, driveTrainSpeedController4));
	static constexpr double kVoltsPerDegreePerSecond = 0.0128;

    driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.5);
        driveTrainRobotDrive41->SetMaxOutput(1.0);
        gyro->SetSensitivity(kVoltsPerDegreePerSecond);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
